### ISSUE TITLE
Talk for 8th Jan

### ISSUE THREAD

**Issue by mbourne** [SingaporeCSS/talk.css#10]
Proposed talk title
Text on Images - a Saga

Brief description of talk (few lines can liao)

How to convince developers (and their bosses) to choose better alternatives to poster-style advertising mails?

Estimated length of talk
10 min

About you
---
**Full name**: Murray Bourne

**Twitter or Github username**: @intmath

**Short bio (1-liner is good)**: Still coding after all these years...

**Comment by huijing** [comment]
Thank you for your lovely talk! Can you please share the link to your slides?

**Comment by mbourne** [comment]
Not much there, but here you go:

https://docs.google.com/presentation/d/1EOz9B97UTAJbd4RZcHNon77v24D5PwDNQn6BkLKjjrY/edit?usp=sharing

**Comment by huijing** [comment]
Thank you!
