### ISSUE TITLE
`butt` is a valid CSS value.

### ISSUE THREAD

**Issue by Tzyinc** [SingaporeCSS/talk.css#13]
Proposed talk title
---
`butt` is a valid CSS value.

Brief description of talk (few lines can liao)
---
On top of the very important title, I will also pad it out with some information and demo regarding styling svgs using css. 

Estimated length of talk
---
6min 40secs

About you
---
**Full name**: Ten Zhi-Yang

**Twitter or Github username**: @tzyinc

**Short bio (1-liner is good)**: A senior software engineer at shopee who wants to say "`butt` is a valid css value" in public

**Comment by huijing** [comment]
🍑🍑🍑
