### ISSUE TITLE
Mask Go Where, Flu Go Where, Gahmen Go Where?

### ISSUE THREAD

**Issue by Milleus** [SingaporeCSS/talk.css#14]
Proposed talk title
---
Mask Go Where, Flu Go Where, Gahmen Go Where?

Brief description of talk (few lines can liao)
---
1. Introduction to self and GovTech
2. How we developed Mask Go Where and Flu Go Where in several hours (story time)
3. Issues faced (get to know what's happening inside.. shhh...)
3. What other Go Wheres are in development (shhh...)
4. Learning points and shameless brag

Estimated length of talk
---
10 - 15mins?

When you want to give said talk
---
Up to you :smirk:

About you
---
**Full name**: Quah Shiwei Dave

**Twitter or Github username**: @milleus

**Short bio (1-liner is good)**: Full stack "Daveloper" at GovTech building stuff for the government. Strong preference for front-end. I tell computers what to do, sometimes they listen.

**Comment by huijing** [comment]
@Milleus You are now the reigning winner of best talk title of Talk.CSS until anyone else can come up with something better. 🏆🏆🏆

**Comment by huijing** [comment]
Tok gong talk. Puts the Singapore in SingaporeCSS.
