### ISSUE TITLE
Writing Responsible CSS

### ISSUE THREAD

**Issue by Neha** [SingaporeCSS/talk.css#15]
Proposed talk title: Writing Responsible CSS
---

Brief description of talk (few lines can liao): When it comes to performance and accessibility, developers ignore CSS but they don't know that CSS is also one of the pillars of the web application. Writing responsible CSS wrt to performance and accessibility.

Details: https://docs.google.com/presentation/d/1LSKVL8wB6frDso_YkYhnQ1pWxLG4xJ5QwDbgsjPY1LU/edit?usp=sharing
---

Estimated length of talk : 40mins
---

When you want to give said talk: Weekday after 5:00 PM (IST) and weekends anytime
---

About you
---
**Full name**: Neha Sharma

**Twitter or Github username**: Neha

**Short bio (1-liner is good)**: UI Manager and Calligraphy lover from India.

**Comment by huijing** [comment]
Hello Neha! Are you in Singapore or would you like to dial-in? Also, do you think you could give a slightly shorter version (like 30min)?

**Comment by Neha** [comment]
Hello,

I will dial-in. Sure I ll make it for a short duration

Thanks,
Neha

**Comment by huijing** [comment]
Hello Neha,
I see you're speaking at Women Of React :)
Just wanted to ask if there was a good time for you to do a test call?

**Comment by Neha** [comment]
Hello,

What is the date for the Meetup?

Thanks,
Neha

**Comment by huijing** [comment]
It's 6 May, Wednesday

**Comment by huijing** [comment]
Hello @Neha, can I confirm you for this Wed?

**Comment by huijing** [comment]
Did not happen.
