### ISSUE TITLE
Modern workflows with JAMstack and ZEIT

### ISSUE THREAD

**Issue by sarupbanskota** [SingaporeCSS/talk.css#16]
Proposed talk title
---

Modern workflows with JAMstack and ZEIT

Brief description of talk (few lines can liao)
---

I'll talk about my personal journey learning programming and developing websites, and how it has evolved in the last few years. I'll describe what the JAMstack is, some cool products I've seen built with the JAMstack, and demonstrate how productive it can make you.

While not strictly a CSS talk, if you build websites and frontends, this talk is for you. 

Estimated length of talk
---

20 minutes

When you want to give said talk
---

1 April

About you
---

[GitHub](https://github.com/sarupbanskota) | [Twitter](https://twitter.com/sarupbanskota)

**Short bio (1-liner is good)**:

I run Growth at [ZEIT](https://zeit.co). My biggest weakness is Chicken Rice.

**Comment by huijing** [comment]
Hello! Is there any way you could put more emphasis on CSS for this talk? Otherwise, it seems like your talk would be a better candidate for our sister meetup Talk.JS, https://github.com/SingaporeJS/talk.js

**Comment by sarupbanskota** [comment]
Sure no problem!

I saw a tweet about shortage of speakers and figured I'd propose a talk to help out. Looks like there are quite a few relevant proposals now, so all good!
