### ISSUE TITLE
Using the CSS Nesting spec today

### ISSUE THREAD

**Issue by JohnAlbin** [SingaporeCSS/talk.css#17]
Proposed talk title
---
Using the CSS Nesting spec today

Brief description of talk
---

If you've used Sass, you know the advantages of nested rulesets. You may not know that there is an effort to bring nesting to the CSS spec. In fact, 
the CSS Nesting spec was upgraded from "Level 0" to a "Level 1" W3C Editor's Draft last year.

While no browsers have implemented the spec yet, you can use this new syntax today thanks to clever PostCSS plugins. It feels good to learn and implement new CSS syntax and it feels even better to help push CSS and HTML specs through the process and see them get implemented in browsers.

In this session, we will discuss:
* why CSS nesting is cool
* what's in the CSS nesting spec
* what's not in the CSS nesting spec
* how you can implement CSS nesting syntax in your code today
* how you can help move the spec discussion forward
* how to easily track CSS specs in general

Estimated length of talk
---
15-30 minutes; it can be shortened or lengthened as needed.

When you want to give said talk
---
April

About you
---
**Full name**: John Albin Wilkins

**Github username**: @JohnAlbin
**Twitter username**: [@JohnAlbin](https://twitter.com/JohnAlbin)

**Short bio**: John has been a web developer since 1993, so he's seen (and forgotten) a lot. He's also shared his experiences with open-source code and over 80 talks across 4 continents.

**Comment by JohnAlbin** [comment]
Just to be clear, I would be presenting this remotely from Taiwan where I live. I've given several online presentations over the years.

**Comment by huijing** [comment]
Hello! Thank you so much for being willing to speak. Can I confirm that you will be available to dial-in on 1 April?

**Comment by JohnAlbin** [comment]
> Can I confirm that you will be available to dial-in on 1 April?

Yep! I'm available Wednesday, April 1 at 7pm.

**Comment by huijing** [comment]
Hello John, are you okay to keep your talk to 20min or less?

**Comment by JohnAlbin** [comment]
> Hello John, are you okay to keep your talk to 20min or less?

Yep. Can do.

**Comment by huijing** [comment]
Hello John,
Would you be free for a test call anytime in the following days before Talk.CSS?

**Comment by JohnAlbin** [comment]
> Would you be free for a test call anytime in the following days before Talk.CSS?

Tuesday would work best. Any time after 10am. Zoom?

**Comment by huijing** [comment]
yes, here's the test link scheduled for 1030am tuesday morning
https://zoom.us/j/3872776449

**Comment by huijing** [comment]
just one more thing, do you mind sharing the link to your slides?

**Comment by JohnAlbin** [comment]
> just one more thing, do you mind sharing the link to your slides?

https://www.slideshare.net/JohnAlbin/using-the-css-nesting-spec-today

**Comment by huijing** [comment]
Thank you once again for your amazing talk :)
