### ISSUE TITLE
Designing for Inclusion with Media Queries

### ISSUE THREAD

**Issue by ericwbailey** [SingaporeCSS/talk.css#18]
Designing for Inclusion with Media Queries
---

Did you know that media queries aren’t just limited to screen size? This talk will dive into some lesser-known media queries that can help developers and designers create experiences for people browsing the web using assistive technologies.

Estimated length of talk
---

45 minutes

When you want to give said talk
---

I am submitting for the April 1st talk slot, as discovered via [this tweet](https://twitter.com/singaporecss/status/1240103864776265728).

About you
---
Eric Bailey

@ericwbailey

Eric is a designer at thoughtbot, accessibility and inclusive design advocate, and maintainer of The A11Y Project.

Note: I have [given this talk previously](https://noti.st/ericwbailey/QxdLmO/designing-for-inclusion-with-media-queries) at Inclusive Design 24 and Boston CSS.

**Comment by huijing** [comment]
Hello Eric! I'm so honoured that you would submit a talk for Talk.CSS
One little thing, I'm in a Singapore timezone which would be 12 hours ahead of you (I'm assuming you're on EDT), and our meet-up starts around 715pm or so, which ends up being 715am your time.
Are you okay with the timezone thing?

**Comment by ericwbailey** [comment]
Yup, no problem at all!

**Comment by huijing** [comment]
Amazing, one more thing, do you think you could do a shorter version of the talk? Maybe 30min? It's totally fine if you can't, we'll just start earlier.

**Comment by ericwbailey** [comment]
Reviewing the slides, I think I could probably shave the custom properties bit off and dial it down to 30 minutes. I'll do a dry run in a bit and reply here if otherwise.

**Comment by huijing** [comment]
Thank you so much :)

**Comment by ericwbailey** [comment]
Would it be possible to do 45 minutes? There's a couple new features from the level 5 spec I'd like to incorporate.

**Comment by huijing** [comment]
Sure, I'll start earlier :)

**Comment by ericwbailey** [comment]
Oh wow, thank you so much. I really appreciate it 🎉

**Comment by huijing** [comment]
Hello Eric, do you have some time before the day itself for a test call?

**Comment by ericwbailey** [comment]
Yup! What time were you thinking?

**Comment by huijing** [comment]
Actually are you good for a quick one in half an hour? at 12?

**Comment by ericwbailey** [comment]
Sounds perfect. My email is `removed`.

**Comment by huijing** [comment]
Will send you the zoom link, thank you!

**Comment by huijing** [comment]
just one more thing, do you mind sharing the link to your slides?

**Comment by ericwbailey** [comment]
Not at all. Just emailed you a share link, and I'll make a PDF when the talk is done if you want.

**Comment by huijing** [comment]
Thank you once again for your amazing talk. :)

**Comment by ericwbailey** [comment]
No way, thank you for such a great opportunity! I had so much fun 😀
