### ISSUE TITLE
What's New in HTML

### ISSUE THREAD

**Issue by cliener** [SingaporeCSS/talk.css#19]
What's New in HTML
---

One of the strengths of the web is there are multiple ways to achieve the same thing. The challenge then for us developers is to find the best way

HTML didn't stop at version 5 and it continues to evolve. Chris Lienert will review a number of HTML elements and attributes that are new and (somewhat!) ready to be used.

---

25-30 minutes

---

May something something

---

About you
---
**Full name**: It me

**Twitter or Github username**:

**Short bio (1-liner is good)**:
Chris apparently has the wrong qualifications and shouldn't be here. No one told him though, and despite not wanting to work with computers, he became a web developer anyway.

**Comment by huijing** [comment]
AH-MAZING talk. 5 stars.
