### ISSUE TITLE
How to build this Spinning pacman shit

### ISSUE THREAD

**Issue by zellwk** [SingaporeCSS/talk.css#20]
How to build this Spinning pacman shit
---
Refer to: https://twitter.com/zellwk/status/1243122788824518656?s=20

---

Estimated length of talk
---
10m

When you want to give said talk
---
6 May

About you
---
**Full name**: Zell Liew Wei Keat

**Twitter or Github username**: @zellwk

**Short bio (1-liner is good)**: Use existing

**Comment by huijing** [comment]
Excellently entertaining. 5 stars.
