### ISSUE TITLE
The curious case of Flexbox 🧐

### ISSUE THREAD

**Issue by vishaag** [SingaporeCSS/talk.css#21]
Proposed talk title
---
The curious case of Flexbox 🧐

Brief description of talk (few lines can liao)
---
What exactly is the Flexbox and what was it made to solve 🧐? When should you use it and when should you not use it? Come learn the different properties and use-cases of flexbox with a relatable example!

_< shameless plug >_ 🙈
_This will also be a part of the CSS Bytes series, Ep. 02. on my YouTube channel._
_</ shameless plug >_

Estimated length of talk
---

~10-15 mins

When you want to give said talk
---

June 

About you
---
**Full name**: Vishaag Suriyanarayanan

**Twitter or Github username**: 🐦 : [@vishaag](https://twitter.com/vishaag) / 🐙: [github.com/vishaag](https://github.com/vishaag)

**Short bio (1-liner is good)**: Vishaag is a CS Engineer who moved to Singapore for his Master's degree, but found Web Development more interesting than his courses.

**Comment by huijing** [comment]
When Vishaag goes viral, we want to state that we were here first.
