### ISSUE TITLE
Layouts with CSS Grid

### ISSUE THREAD

**Issue by olivia-ng** [SingaporeCSS/talk.css#22]
Proposed talk title
---
Layouts with CSS Grid

Brief description of talk (few lines can liao)
---
Coding a CSS Grid layout (not live coding, just something like it) and more info/examples on how people are using CSS Grid.

Estimated length of talk
---
15-20 minutes?

When you want to give said talk
---

June lo

About you
---
**Full name**: Olivia Ng

**Twitter or Github username**: https://twitter.com/meowlivia_

**Short bio (1-liner is good)**: A "designer who codes", but somehow ended up coding more than designing. Afraid of JavaScript.

**Comment by huijing** [comment]
5 stars. Would definitely buy again.
