### ISSUE TITLE
Responsive Layouts with CSS Grid

### ISSUE THREAD

**Issue by vishaag** [SingaporeCSS/talk.css#23]
Proposed talk title
---
Responsive Layouts with CSS Grid

Brief description of talk (few lines can liao)
---
CSS Grid is pretty cool for a lot of things. Let's see some examples (+live coding) where you can use it to make responsive designs! 

Estimated length of talk
---
20 mins

When you want to give said talk
---
August

About you
---
**Full name**: Vishaag Suriyanarayanan

**Twitter or Github username**: 🐦 :  [@vishaag](https://twitter.com/vishaag) / 🐙: [github.com/vishaag](https://github.com/vishaag)

**Short bio (1-liner is good)**: Vishaag is a CS Engineer who moved to Singapore for his Master's degree, but found Web Development more interesting than his courses.

**Comment by huijing** [comment]
Thanks for the ah-mazing talk. 💙
