### ISSUE TITLE
Third party CSS is not safe

### ISSUE THREAD

**Issue by tanhauhau** [SingaporeCSS/talk.css#24]
Third party CSS is not safe
---

As titled. If you can't wait for the talk, read https://jakearchibald.com/2018/third-party-css-is-not-safe/. My talk will be a live demoing all the examples.

---

Estimated length of talk: 15mins
---

When you want to give said talk: Sep 2
---

About you
---
**Full name**: Tan Li Hau

**Twitter or Github username**: twitter: @lihautan | github: @tanhauhau

**Short bio (1-liner is good)**: Hi, I'm Li Hau. Frontend Engineer at Shopee.

**Comment by huijing** [comment]
Oh, this sounds fun! Looking forward to it :)

**Comment by huijing** [comment]
Thanks for the great talk. Can you send me link your slides? @tanhauhau

**Comment by tanhauhau** [comment]
https://lihautan.com/third-party-css-is-not-safe/

**Comment by huijing** [comment]
Thank you!
