### ISSUE TITLE
SCSS Techniques (Talk on 2 October 2019 at Singapore CSS 44th Meetup) 

### ISSUE THREAD

**Issue by Calebyang93** [SingaporeCSS/talk.css#4]
Applying SASS in Responsive Web Development using Javascript Frameworks 
---

SASS has been around recently. It is important for us to understand how to make use of SASS to beautify our websites to integrate with our html and javascript files in our web projects. 
---

About you
---
Caleb Yang,

**Twitter or Github username**:
Github: https://github.com/Calebyang93
Facebook: https://facebook.com/therealcalebyang
linkedin: https://www.linkedin.com/in/caleb-yang-14786137/

**Short bio (1-liner is good)**:
Caleb is a self taught developer who is exploring his potential to guide people as a financial adviser. In his free time, he volunteers with IMH achievers to bring joy to the patients and those struggling with mental issues. He believes in constantly learning technology to building solutions to address problems. He is currently working on 2 projects, 1 being a cryptocurrency wallet with python scripts and doing frontend development for displaying results for queries.

**Comment by Calebyang93** [comment]
[SCSS Talk - CSS Meetup Oct 2019.pptx](https://github.com/SingaporeCSS/talk.css/files/3671971/SCSS.Talk.-.CSS.Meetup.Oct.2019.pptx)


The slides can also be found on google slides: https://docs.google.com/presentation/d/1-mfRTfAWZJsbnuv_pGKAkyNZW7HiG0hgTFU_LBmX2CE/edit#slide=id.g644f339c41_0_6

**Comment by Calebyang93** [comment]
@huijing @wgao19 
Please download the slides or get access to the google slides for the 2 oct CSS meetup at govtech hive.

**Comment by huijing** [comment]
Presented at Talk.CSS #44
