### ISSUE TITLE
Introduction to Variable Fonts

### ISSUE THREAD

**Issue by pregnantboy** [SingaporeCSS/talk.css#5]
Proposed talk title
---
Introduction to Variable Fonts

Brief description of talk (few lines can liao)
---
The advantages of using variable fonts and how it can simplify web development

About you
---
**Full name**:
Ian Chen
**Twitter or Github username**:
github.com/pregnantboy
**Short bio (1-liner is good)**:
Software engineer in Open Government Products

**Comment by wgao19** [comment]
hi @pregnantboy do u have a link to your slides?

**Comment by huijing** [comment]
Presented at Talk.CSS #44
