### ISSUE TITLE
Learning to Count with CSS (we’re still here edition)

### ISSUE THREAD

**Issue by thchia** [SingaporeCSS/talk.css#6]
Proposed talk title
---
Learning to Count with CSS

Brief description of talk (few lines can liao)
---
People say CSS is not a real programming language. People say that if you need to count stuff use JavaScript. In this talk I dispel such myths and will blow at least my own mind as I show how to count with CSS (tldr it’s a quick overview of the `counter` property. It’s gonna be really short ⚡️ ).

About you
---
**Full name**:
Chia Hon-Wen Thomas Hamilton 谢宏文 (don’t say never give full name)

**Twitter or Github username**:
@th__chia 

**Short bio (1-liner is good)**:
Front End Developer. Lover not a hater.

Loves:
- SingaporeCSS
- React also not bad

Hates:
N/A

**Comment by huijing** [comment]
omg @thchia why u my mindtwin? ❤️

**Comment by huijing** [comment]
@thchia can send the link to your codesandboxes?

**Comment by thchia** [comment]
Eh sorry will post this weekend.

**Comment by huijing** [comment]
nvm I Google stalked u and found the links 😏
