### ISSUE TITLE
Tools for Rapid CSS development

### ISSUE THREAD

**Issue by sathishk** [SingaporeCSS/talk.css#7]
Tools for Rapid CSS development

I would like to talk about the tools that can help us to use CSS effectively to build web applications.

**Full name**: Sathish Kumar Thiyagarajan

**Twitter or Github username**: sathishk

**Short bio (1-liner is good)**: Software **ENGINEER**

**Comment by huijing** [comment]
How long would your talk be? We have quite a few speakers this time and would like to manage the time.

**Comment by sathishk** [comment]
@huijing mine should take around 20 to 25 mins

**Comment by huijing** [comment]
ok, do you mind keeping it to 20 min?

**Comment by sathishk** [comment]
Sure @huijing

**Comment by huijing** [comment]
@sathishk can you please send me the link to your slides?

**Comment by sathishk** [comment]
@huijing Slides are available at https://sathishk.github.io/presentations/css-tools/slides.pdf

It was great talking at CSS meetup. Thanks for the opportunity

**Comment by huijing** [comment]
You're more than welcome, and thank YOU for speaking :)
