### ISSUE TITLE
Why would I use Javascript for my styling

### ISSUE THREAD

**Issue by eriknguyen** [SingaporeCSS/talk.css#8]
Proposed talk title
---
Why would I use Javascript for my styling (TBC)

Brief description of talk (few lines can liao)
---
From traditional CSS to CSS-in-JS, we will discuss why we would explore the new way of writing styles and how to take advantages of it.

About you
---
**Full name**: Erik Nguyen Khanh

**Twitter or Github username**: eriknguyen (@_eriknguyen)

**Short bio (1-liner is good)**: Front End Engineer at [Rakuten Viki](https://viki.com)

**Comment by huijing** [comment]
How long do you think the talk will be?

**Comment by eriknguyen** [comment]
> How long do you think the talk will be?

@huijing It will be 20-25 minute talk, I might take 5 mins for Q&A too. So I would say I'll take 30 mins in total

**Comment by huijing** [comment]
Hey Erik, thanks for the update, we do have a number of speakers this time, do you mind trying to keep to 20 min?

**Comment by eriknguyen** [comment]
> Hey Erik, thanks for the update, we do have a number of speakers this time, do you mind trying to keep to 20 min?

Sure. I will try!

**Comment by huijing** [comment]
@eriknguyen can you please send me a link to your slides?

**Comment by eriknguyen** [comment]
@huijing Here you go: https://docs.google.com/presentation/d/1wS92luLtqhBXET7Q7ZVsMArZ7eyNplgEYSsoSIAabPg/edit?usp=sharing

**Comment by huijing** [comment]
Thank you so much :)
