### ISSUE TITLE
UX Matters

### ISSUE THREAD

**Issue by sathishk** [SingaporeCSS/talk.css#9]
When it comes to UX,  At one side, We see companies that think 

> UX Matters a lot

On the other side, companies that think 

> does it matter al all ?!.  

I want to share my views of **why and for whom UX _(really)_ Matters.**

Estimated length of talk 20 Mins

**Full name**: Sathish Kumar Thiyagarajan

**Twitter or Github username**: sathishk

**Short bio (1-liner is good)**: Software ENGINEER

**Comment by huijing** [comment]
Hello Satish, are you still up for giving this talk on Wednesday? Also, will any CSS be mentioned in the talk?

**Comment by huijing** [comment]
Thanks for your talk :)
Can you please share the link to your slides?
